title: Brief Portfolio - John Walasik
author: John Walasik
email: jfwalasik@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Some brief writing samples, technical writing samples (SOPs, work Instructions, Guidelines, Checklists), and legal writing samples. Coming soon: soup recipes (I make delicious soup -- chicken with kale; onion gratinee; cream of vegetable; Italian wedding soup; minestrone.
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  JFWalasik # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
